### ISSUE TITLE
 sippy_cup could locate sipp

### ISSUE THREAD

**Issue by Tochemey** [mojolingo/sippy_cup#80]
Hello,

I have an issue running sippy_cup. 
I have installed sipp following the documentation on their site and I installed sippy_cup too according the readme. However whenever I run the sippy_cup against my scenario file I got the following error: 

```
# sippy_cup -r config.yml 
I, [2015-05-21T15:23:31.964131 #29070]  INFO -- : Preparing to run SIPp command: sudo $(which sipp) -p 8836 -sf /tmp/scenario20150521-29070-1y4lvvp -l 10 -m 20 -r 5 -s 233208063817 -i 192.168.88.135 192.168.254.220:5080
sudo: invalid option -- 'f'usage: sudo -h | -K | -k | -Vusage: sudo -v [-AknS] [-g group] [-h host] [-p prompt] [-u user]usage: sudo -l [-AknS] [-g group] [-h host] [-p prompt] [-U user] [-u user][command]usage: sudo [-AbEHknPS] [-r role] [-t type] [-C num] [-g group] [-h host] [-pprompt] [-u user] [VAR=value] [-i|-s] [<command>]usage: sudo -e [-AknS] [-r role] [-t type] [-C num] [-g group] [-h host] [-pprompt] [-u user] file ...I, [2015-05-21T15:23:31.985330 #29070]  INFO -- : Test completed successfully but some calls failed.
```

It seems that sippy_cup could not locate the sipp executable even though I am running under root. Please educate me on how to use them.

**Comment by bklang** [comment]
If sippy-cup cannot find the `sipp` executable, most likely it is not in the PATH. What do you get when you type `which sipp`?

**Comment by Tochemey** [comment]
I got nothing

**Comment by Tochemey** [comment]
to run sipp I have to go the sipp folder.

**Comment by bklang** [comment]
You'll need to add the directory that contains the sipp executable to your PATH environment variable. Assuming you have the sipp executable at `/home/tochemey/sipp-3.4` then your PATH would be something like this:

```bash
export PATH=$PATH:/home/tochemey/sipp-3.4
sippy_cup -r config.yml
```

**Comment by Tochemey** [comment]
Ok Thank you I added it to /etc/environment
