### ISSUE TITLE
Use tls if destination port is 5061

### ISSUE THREAD

**Issue by ghost** [mojolingo/sippy_cup#88]
At the moment sippy_cup setup the scenario file to use udp despite the destination port is set to 5061.

**Comment by benlangfeld** [comment]
You need to set the `transport_mode` option to either `l1` or `ln` In order to use TLS. There is nothing special about port 5061 which should trigger this to be set automatically.

**Comment by bklang** [comment]
You can see the full list of transports available in the [SIPp documentation](http://sipp.sourceforge.net/doc/reference.html#Transport+modes)
